### ISSUE TITLE
m ERR! gyp ERR!

### ISSUE THREAD

**Issue by Sindoes** [doenerium6969/doenerium-fixed#3]
C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder>echo off
NOTE: Make sure you have Node.js v18.15.0 and Native Tools (including Chocolatey) installed aswell! Otherwise the .exe won't work correctly.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated electron-rebuild@3.2.9: Please use @electron/rebuild moving forward.  There is no API change, just a package name change
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm notice
npm notice New major version of npm available! 9.5.0 -> 10.2.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice
npm ERR! code 1
npm ERR! path C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-hide-console-window
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.5 found at "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.15.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v18.15.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.15.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.15.0/win-x64/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
npm ERR! gyp ERR! stack     at C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\find-visualstudio.js:401:16
npm ERR! gyp ERR! stack     at C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WDAGUtilityAccount\\Desktop\\doenerium-V2.builder\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\WDAGUtilityAccount\Desktop\doenerium-V2.builder\node_modules\node-hide-console-window
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WDAGUtilityAccount\AppData\Local\npm-cache\_logs\2023-12-02T06_57_16_237Z-debug-0.log

added 127 packages in 11s

22 packages are looking for funding
  run `npm fund` for details

added 99 packages in 6s

14 packages are looking for funding
  run `npm fund` for details
[

**Comment by Poolj2023** [comment]
Bro, I was able to compile it, it works perfectly, but after 20 days Discord disables my account. Is there a way so that Discord doesn't disable my account? Could the records go to Telegram?

**Comment by doenerium6969** [comment]
Uninstall old python and download [Python 3.10](https://www.python.org/ftp/python/3.10.10/python-3.10.10-amd64.exe)

**Comment by Poolj2023** [comment]
Bro, Doenerium works perfectly, but after 20 days Discord disables my account. Is there a way for Discord not to disable my account? since I did it 2 times and the same thing happened to me...
